FROM centos:6.9
MAINTAINER gitclientaravind@gmail.com
RUN cd /tmp/ && yum install wget -y && wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz && tar -xvf apache-tomcat-8.5.32.tar.gz && mv apache-tomcat-8.5.32.tar.gz /tmp/tomcat8 
