---
- name: working with script module
  hosts: ansi-server
  tasks:
    - name: using script module
      script: ./for.py
      register: output

    - debug: msg="{{output.stdout_lines}}"

    - set_fact: myvar="{{output.stdout_lines[2]}}" 
      # one_fact: true
      #   other_fact: false
      #   myvar= "{{output.stdout_lines[2]}}"       
    - name: checking the value of myvar
      command: echo"{{myvar}}"

